import { FieldDef, QueryResultRow, sql } from "@vercel/postgres"
import { IProject, Project as TProject, ITable, TableNames, SelectedColumns, TableOptions, ProjectEntities, ProjectCard } from "../types"

async function seed(cb: Promise<void>) {
  // Create the enums
  await sql`CREATE TYPE project_category AS ENUM('Front End Development','App Development')`

  await sql`
      CREATE TABLE IF NOT EXISTS projects(
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(255) UNIQUE NOT NULL,
        category project_category NOT NULL,
        cover_image VARCHAR(255) NOT NULL,
        description VARCHAR(255) NOT NULL,
        live_url VARCHAR(255) NOT NULL,
        github_url VARCHAR(255) NOT NULL,
        created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        youtube_url VARCHAR(255) NOT NULL,
        problem_title text NOT NULL,
        problem_description text NOT NULL,
        solution_title text NOT NULL,
        solution_description text NOT NULL
      )
    `

  await sql`
      INSERT INTO projects(name, slug, category, cover_image, description, live_url, github_url, youtube_url, problem_title, problem_description, solution_title, solution_description)
      VALUES
      (
        'tribe',
        'tribe',
        'App Development',
        'https://res.cloudinary.com/anthonygayflor/image/upload/v1689311224/login-bg-min_rlfmic.png',
        'a social media platform for exclusive social groups centered around a shared passion',
        'https://tribe-next-js.vercel.app/',
        'https://github.com/anthonyg56/Tribe-NextJS',
        'https://youtu.be/tTLaZmiHzao',
        'Social media lacks an authentic enviorment for intimate online connections',
        'The majority of the content that people view on social media is on a single timeline. It is posts generated by either AI, someone you follow/is subscribed to, or have added as a friend. The problem with this approach is that so many people have become overly identified with their online personas. All in an effort to make their post seem more exciting or appealing than it actually is and get the spotlight for most likes or views.  Problems like this make It difficult to create authentic shared intimate moments online with those you are close to. The reason is that key parts of intimacy like inclusion, authenticity, and the freedom to share vulnerabilities are hard to achieve given how social media lacks an integral environment that allows it.',
        'Private online spaces called Tribes.',
        'People want to be able to enjoy what they love online in an intimate fashion just like in real life. With Tribe, users can create or join multiple private spaces built like conventional social media, but only for an exclusive group of people.  It's much easier to share intimate moments this way because they're centered around a shared passion, interest, or goal within a private setting. Each Tribe will have an owner and is customizable to suit varying needs, whether that be visual or systematic.',
      ),
      (
        'hypersets',
        'hypersets',
        'App Development',
        '/home-light.gif',
        'An online platform for the HyperX community to store, discover, and illuminate their pc's peripheral setup',
        'https://hyper-sets.com',
        'https://github.com/anthonyg56/HyperSets',
        '',
        'Trying to find custom presets for hyperx products is a hassell',
        'There are talented people creating cool profiles, but dont have a platform to share it on. Unless they are capable of building a website to host their presets; chances are it would get uploaded on a public form like reddit and lost within the sea of content. Thus making it a hassel to explore alternatives outside of what the manufacture provides since alot of custom profiles are scattered on the web.',
        'A centralized location for custom presets',
        'My theory was if users had a central platform to upload, share, and download custom NGenuity RGB profiles; along with an incentive of getting paid per download of their preset. Not only would this help organize profiles on the web, the number of profiles availables would increase as well.'
      )
    `

  // Returning the objectings runs the queries automatically
  return cb
}
}



export async function seedUser(cb: Promise<void>) {
  // Create the enums
  await sql`CREATE TYPE project_category AS ENUM('Front End Development','App Development')`

  await sql`
   CREATE TABLE IF NOT EXISTS projects(
     id SERIAL PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
     slug VARCHAR(255) UNIQUE NOT NULL,
     category project_category NOT NULL,
     cover_image VARCHAR(255) NOT NULL,
     description VARCHAR(255) NOT NULL,
     live_url VARCHAR(255) NOT NULL,
     github_url VARCHAR(255) NOT NULL,
     created_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
     youtube_url VARCHAR(255) NOT NULL,
     problem_title text NOT NULL,
     problem_description text NOT NULL,
     solution_title text NOT NULL,
     solution_description text NOT NULL
   )
 `

  await sql`
   INSERT INTO projects(name, slug, category, cover_image, description, live_url, github_url, youtube_url, problem_title, problem_description, solution_title, solution_description)
   VALUES
   (
     'tribe',
     'tribe',
     'App Development',
     'https://res.cloudinary.com/anthonygayflor/image/upload/v1689311224/login-bg-min_rlfmic.png',
     'a social media platform for exclusive social groups centered around a shared passion',
     'https://tribe-next-js.vercel.app/',
     'https://github.com/anthonyg56/Tribe-NextJS',
     'https://youtu.be/tTLaZmiHzao',
     'Social media lacks an authentic enviorment for intimate online connections',
     'The majority of the content that people view on social media is on a single timeline. It is posts generated by either AI, someone you follow/is subscribed to, or have added as a friend. The problem with this approach is that so many people have become overly identified with their online personas. All in an effort to make their post seem more exciting or appealing than it actually is and get the spotlight for most likes or views.  Problems like this make It difficult to create authentic shared intimate moments online with those you are close to. The reason is that key parts of intimacy like inclusion, authenticity, and the freedom to share vulnerabilities are hard to achieve given how social media lacks an integral environment that allows it.',
     'Private online spaces called Tribes.',
     'People want to be able to enjoy what they love online in an intimate fashion just like in real life. With Tribe, users can create or join multiple private spaces built like conventional social media, but only for an exclusive group of people.  It's much easier to share intimate moments this way because they're centered around a shared passion, interest, or goal within a private setting. Each Tribe will have an owner and is customizable to suit varying needs, whether that be visual or systematic.',
   ),
   (
     'hypersets',
     'hypersets',
     'App Development',
     '/home-light.gif',
     'An online platform for the HyperX community to store, discover, and illuminate their pc's peripheral setup',
     'https://hyper-sets.com',
     'https://github.com/anthonyg56/HyperSets',
     '',
     'Trying to find custom presets for hyperx products is a hassell',
     'There are talented people creating cool profiles, but dont have a platform to share it on. Unless they are capable of building a website to host their presets; chances are it would get uploaded on a public form like reddit and lost within the sea of content. Thus making it a hassel to explore alternatives outside of what the manufacture provides since alot of custom profiles are scattered on the web.',
     'A centralized location for custom presets',
     'My theory was if users had a central platform to upload, share, and download custom NGenuity RGB profiles; along with an incentive of getting paid per download of their preset. Not only would this help organize profiles on the web, the number of profiles availables would increase as well.'
   )
 `

  // Returning the objectings runs the queries automatically
  return cb
}